language: ruby
services: mongodb
sudo: false
rvm:
  - 2.0.0
  - 2.2.0
  - ruby-head
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/5.0.gemfile

#matrix:
#  allow_failures:
#    - rvm: jruby-19mode

env:
  global:
    secure: Uco0icktul54bwvQOP4PHME1fKIkWvJTBSYYgLxkJfpT6epeuzRMTs+/vH1Ysvs5s4E2hx2yAYyu2VEu3R5sjxkuPpvQFUJbr8Vxm7g2DczeIL3WlZiSctt0zqJqToyhIW8Fpsza2/GSr1eHkMIk6rnWp4miARtbGAXpH5K4d2s=
